<?php

/**
 * This is the model base class for the table "vote".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Vote".
 *
 * Columns in table "vote" available as properties of the model,
 * followed by relations of table "vote" available as properties of the model.
 *
 * @property integer $id
 * @property integer $weight
 * @property integer $user_nr
 * @property integer $featureRequest_nr
 *
 * @property AbstractUser $userNr
 * @property FeatureRequest $featureRequestNr
 */
abstract class BaseVote extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'vote';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Vote|Votes', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('weight, user_nr, featureRequest_nr', 'required'),
			array('weight, user_nr, featureRequest_nr', 'numerical', 'integerOnly'=>true),
			array('id, weight, user_nr, featureRequest_nr', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'userNr' => array(self::BELONGS_TO, 'AbstractUser', 'user_nr'),
			'featureRequestNr' => array(self::BELONGS_TO, 'FeatureRequest', 'featureRequest_nr'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'weight' => Yii::t('app', 'Weight'),
			'user_nr' => null,
			'featureRequest_nr' => null,
			'userNr' => null,
			'featureRequestNr' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('weight', $this->weight);
		$criteria->compare('user_nr', $this->user_nr);
		$criteria->compare('featureRequest_nr', $this->featureRequest_nr);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}