<?php

/**
 * This is the model base class for the table "abstract_message".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AbstractMessage".
 *
 * Columns in table "abstract_message" available as properties of the model,
 * followed by relations of table "abstract_message" available as properties of the model.
 *
 * @property integer $id
 * @property string $title
 * @property string $content
 * @property string $created_time
 * @property integer $abstractUser_id
 *
 * @property AbstractUser $abstractUser
 * @property Comment $comment
 * @property FeatureRequest $featureRequest
 */
abstract class BaseAbstractMessage extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'abstract_message';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AbstractMessage|AbstractMessages', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('title, content, created_time, abstractUser_id', 'required'),
			array('abstractUser_id', 'numerical', 'integerOnly'=>true),
			array('title', 'length', 'max'=>45),
			array('id, title, content, created_time, abstractUser_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'abstractUser' => array(self::BELONGS_TO, 'AbstractUser', 'abstractUser_id'),
			'comment' => array(self::HAS_ONE, 'Comment', 'id'),
			'featureRequest' => array(self::HAS_ONE, 'FeatureRequest', 'id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'title' => Yii::t('app', 'Title'),
			'content' => Yii::t('app', 'Content'),
			'created_time' => Yii::t('app', 'Created Time'),
			'abstractUser_id' => null,
			'abstractUser' => null,
			'comment' => null,
			'featureRequest' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('content', $this->content, true);
		$criteria->compare('created_time', $this->created_time, true);
		$criteria->compare('abstractUser_id', $this->abstractUser_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}